import type { Transaction } from '@/types';

/** Deterministic demo transactions (amounts in minor units / cents). */
export const transactions: Transaction[] = [
  {
    id: 'txn_1001',
    description: 'Assinatura — Aurora Tech',
    type: 'income',
    status: 'completed',
    amount: { amount: 1_840_000, currency: 'BRL' },
    category: 'Assinaturas',
    customerId: 'cus_01',
    date: '2026-06-24T10:12:00.000Z',
  },
  {
    id: 'txn_1002',
    description: 'Infraestrutura cloud',
    type: 'expense',
    status: 'completed',
    amount: { amount: 432_900, currency: 'BRL' },
    category: 'Infraestrutura',
    date: '2026-06-23T16:40:00.000Z',
  },
  {
    id: 'txn_1003',
    description: 'Consultoria de implantação',
    type: 'income',
    status: 'pending',
    amount: { amount: 980_000, currency: 'BRL' },
    category: 'Serviços',
    customerId: 'cus_03',
    date: '2026-06-23T09:05:00.000Z',
  },
  {
    id: 'txn_1004',
    description: 'Folha de pagamento',
    type: 'expense',
    status: 'scheduled',
    amount: { amount: 6_120_000, currency: 'BRL' },
    category: 'Pessoal',
    date: '2026-06-22T08:00:00.000Z',
  },
  {
    id: 'txn_1005',
    description: 'Add-on — Relatórios avançados',
    type: 'income',
    status: 'completed',
    amount: { amount: 163_000, currency: 'BRL' },
    category: 'Add-ons',
    customerId: 'cus_02',
    date: '2026-06-21T14:18:00.000Z',
  },
  {
    id: 'txn_1006',
    description: 'Reembolso — cliente cancelado',
    type: 'refund',
    status: 'completed',
    amount: { amount: 76_000, currency: 'BRL' },
    category: 'Reembolsos',
    customerId: 'cus_05',
    date: '2026-06-20T11:30:00.000Z',
  },
  {
    id: 'txn_1007',
    description: 'Licenças de software',
    type: 'expense',
    status: 'completed',
    amount: { amount: 219_900, currency: 'BRL' },
    category: 'Ferramentas',
    date: '2026-06-19T13:00:00.000Z',
  },
  {
    id: 'txn_1008',
    description: 'Assinatura — Northwind',
    type: 'income',
    status: 'completed',
    amount: { amount: 1_240_000, currency: 'BRL' },
    category: 'Assinaturas',
    customerId: 'cus_04',
    date: '2026-06-18T10:45:00.000Z',
  },
  {
    id: 'txn_1009',
    description: 'Campanha de marketing',
    type: 'expense',
    status: 'pending',
    amount: { amount: 358_000, currency: 'BRL' },
    category: 'Marketing',
    date: '2026-06-17T15:22:00.000Z',
  },
  {
    id: 'txn_1010',
    description: 'Serviços profissionais',
    type: 'income',
    status: 'failed',
    amount: { amount: 540_000, currency: 'BRL' },
    category: 'Serviços',
    customerId: 'cus_06',
    date: '2026-06-16T09:50:00.000Z',
  },
];

/** Most recent transactions for the dashboard activity feed. */
export const recentTransactions: Transaction[] = transactions.slice(0, 6);

export const transactionCategories = [
  'Assinaturas',
  'Serviços',
  'Add-ons',
  'Infraestrutura',
  'Pessoal',
  'Marketing',
  'Ferramentas',
  'Reembolsos',
] as const;
