name: 🐛 Bug report
description: Relate um comportamento inesperado
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Veja o erro
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Ambiente
      placeholder: 'OS, navegador, versão do Node'
