name: 💡 Feature request
description: Sugira uma nova funcionalidade ou melhoria
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / motivação
      description: Qual problema esta feature resolve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solução proposta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
