import type { Customer } from '@/types';

/** Deterministic demo customers (lifetime value in minor units / cents). */
export const customers: Customer[] = [
  {
    id: 'cus_01',
    name: 'Aurora Tech',
    email: 'financeiro@aurora.tech',
    company: 'Aurora Tech',
    avatarUrl: 'https://i.pravatar.cc/80?img=12',
    status: 'active',
    lifetimeValue: { amount: 9_840_000, currency: 'BRL' },
    plan: 'Growth',
    createdAt: '2024-02-10T00:00:00.000Z',
  },
  {
    id: 'cus_02',
    name: 'Northwind',
    email: 'contas@northwind.com',
    company: 'Northwind Traders',
    avatarUrl: 'https://i.pravatar.cc/80?img=33',
    status: 'active',
    lifetimeValue: { amount: 6_120_000, currency: 'BRL' },
    plan: 'Starter',
    createdAt: '2024-05-22T00:00:00.000Z',
  },
  {
    id: 'cus_03',
    name: 'Globex',
    email: 'ap@globex.com',
    company: 'Globex Corporation',
    avatarUrl: 'https://i.pravatar.cc/80?img=5',
    status: 'pending',
    lifetimeValue: { amount: 3_980_000, currency: 'BRL' },
    plan: 'Growth',
    createdAt: '2025-01-15T00:00:00.000Z',
  },
  {
    id: 'cus_04',
    name: 'Initech',
    email: 'billing@initech.com',
    company: 'Initech',
    avatarUrl: 'https://i.pravatar.cc/80?img=15',
    status: 'active',
    lifetimeValue: { amount: 5_260_000, currency: 'BRL' },
    plan: 'Enterprise',
    createdAt: '2023-11-03T00:00:00.000Z',
  },
  {
    id: 'cus_05',
    name: 'Umbrella Co.',
    email: 'finance@umbrella.co',
    company: 'Umbrella Corporation',
    avatarUrl: 'https://i.pravatar.cc/80?img=23',
    status: 'inactive',
    lifetimeValue: { amount: 2_310_000, currency: 'BRL' },
    plan: 'Starter',
    createdAt: '2024-08-19T00:00:00.000Z',
  },
  {
    id: 'cus_06',
    name: 'Soylent',
    email: 'pay@soylent.com',
    company: 'Soylent Industries',
    avatarUrl: 'https://i.pravatar.cc/80?img=8',
    status: 'active',
    lifetimeValue: { amount: 4_540_000, currency: 'BRL' },
    plan: 'Growth',
    createdAt: '2025-03-27T00:00:00.000Z',
  },
];
